# 应用服务 WEB 访问端口
server:
  port: 8080

#spring相关配置
spring:
  application:
    name: primaryms
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimeZone=Asia/Shanghai
    uesrname: root
    password: 1234

#mybatis相关配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml


