# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /myms
#spring相关配置
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#    uesrname: root
#    password: '1234'
#  to sollution time zone problem
#  add serverTimezone=GMT%2B8
#  or
#  show variables like '%time_zone%';
#  set global time_zone='+8:00';
#mybatis相关配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml


